insert into product (id, brand, madein, name, price) values (1, 'Aspirin', 'Croatia', 'Vitamin Fluid', '$7.37');
insert into product (id, brand, madein, name, price) values (2, 'CYCLOBENZAPRINE HYROCHLORIDE', 'Uruguay', 'Clolar', '$9.12');
insert into product (id, brand, madein, name, price) values (3, 'Kali Bichromicum 30c', 'Czech Republic', 'Triamcinolone Acetonide', '$7.68');
insert into product (id, brand, madein, name, price) values (4, 'On Duty Sport', 'Colombia', 'Proctosol-HC', '$9.28');
insert into product (id, brand, madein, name, price) values (5, 'Extra Strength Pain Relief', 'Bolivia', 'MG217 Psoriasis', '$4.59');
insert into product (id, brand, madein, name, price) values (6, 'Medicated', 'Guatemala', 'Minocycline Hydrochloride', '$5.82');
insert into product (id, brand, madein, name, price) values (7, 'Sandostatin', 'Pakistan', 'Pink Eye Relief', '$4.75');
insert into product (id, brand, madein, name, price) values (8, 'Good Neighbor Pharmacy Allergy Relief', 'China', 'Bacsode', '$1.37');
insert into product (id, brand, madein, name, price) values (9, 'DIMENHYDRINATE', 'Cambodia', 'Azor', '$8.77');
insert into product (id, brand, madein, name, price) values (10, 'Aveeno Active Naturals Eczema Therapy Hand', 'Latvia', 'Desmopressin acetate', '$0.17');
insert into product (id, brand, madein, name, price) values (11, 'Allergenic Extracts Standardized Mite', 'Bosnia and Herzegovina', 'Ibuprofen', '$5.09');
insert into product (id, brand, madein, name, price) values (12, 'Eight Hour Cream Lip Protectant SPF 15', 'Panama', 'RANITIDINE', '$6.38');
insert into product (id, brand, madein, name, price) values (13, 'Dextroamphetamine saccharate, amphetamine aspartate, dextroamphetamine sulfate, and amphetamine sulfate', 'Argentina', 'Acetaminophen, Guaifenesin, Phenylephrine Hydrochloride', '$4.73');
insert into product (id, brand, madein, name, price) values (14, 'ANTI-BACTERIAL HAND SANITIZER 2 PACK BLUE DAY SCENTED', 'Mexico', 'Diovan', '$4.63');
insert into product (id, brand, madein, name, price) values (15, 'Fentanyl', 'Ireland', 'Banana Boat Ultra Defense Broad Spectrum', '$7.99');
insert into product (id, brand, madein, name, price) values (16, 'HydrOXYzine Hydrochloride', 'Philippines', 'cold', '$6.86');
insert into product (id, brand, madein, name, price) values (17, 'Mary Kay Tinted Lip Balm Sunscreen SPF 15 Mango', 'Macedonia', 'Gentamicin Sulfate in Sodium Chloride', '$8.09');
insert into product (id, brand, madein, name, price) values (18, 'gent-L-tip', 'Ukraine', 'English Walnut', '$9.19');
insert into product (id, brand, madein, name, price) values (19, 'Sure', 'China', 'ANTIVENIN (MICRURUS FULVIUS)', '$2.26');
insert into product (id, brand, madein, name, price) values (20, 'flu and severe cold and cough', 'Austria', 'LBEL UV DEFENSE 365', '$8.57');
insert into product (id, brand, madein, name, price) values (21, 'Adenosine', 'Greece', 'Hua Tuo', '$7.73');
insert into product (id, brand, madein, name, price) values (22, 'Divalproex Sodium', 'Czech Republic', 'Pseudoephedrine hydrochloride', '$8.47');
insert into product (id, brand, madein, name, price) values (23, 'Imiquimod', 'China', 'Divigel', '$9.17');
insert into product (id, brand, madein, name, price) values (24, 'Candid', 'Bolivia', 'Dry Idea A.Dry Antiperspirant Solid Powder Fresh', '$6.23');
insert into product (id, brand, madein, name, price) values (25, 'EQUALINE MEDICATED WIPES', 'China', 'TIGAN', '$0.31');
insert into product (id, brand, madein, name, price) values (26, 'Renew Dimethicone Skin Protectant', 'China', 'Sulindac', '$4.85');
insert into product (id, brand, madein, name, price) values (27, 'Lithium Carbonate', 'Russia', 'Alfuzosin Hydrochloride', '$8.52');
insert into product (id, brand, madein, name, price) values (28, 'good sense nighttime sleep aid', 'Indonesia', 'Contac Cold and Flu', '$1.24');
insert into product (id, brand, madein, name, price) values (29, 'Femring', 'United States', 'NeoStrata HQ Skin Lightening', '$6.62');
insert into product (id, brand, madein, name, price) values (30, 'Calamine Plus Pramoxine HCl', 'Russia', 'Peptic Relief', '$7.88');
insert into product (id, brand, madein, name, price) values (31, 'Lycoris rubus whitening moisturizing', 'Portugal', 'SUMATRIPTAN', '$6.28');
insert into product (id, brand, madein, name, price) values (32, 'Lemon Fresh Antibacterial Foaming Hand Wash', 'Indonesia', 'PROCTOFOAM', '$9.30');
insert into product (id, brand, madein, name, price) values (33, 'Acetaminophen', 'China', 'Nivea A Kiss of Smoothness Lip Care', '$5.62');
insert into product (id, brand, madein, name, price) values (34, 'Banana Boat UltraMist Kids Tear Free Lotion SPF 50', 'Ukraine', 'SHISEIDO SHEER AND PERFECT COMPACT (REFILL)', '$3.23');
insert into product (id, brand, madein, name, price) values (35, 'Spironolactone', 'New Zealand', 'Pollens - Weeds and Garden Plants, Ragweed, Giant Ambrosia trifida', '$8.71');
insert into product (id, brand, madein, name, price) values (36, 'Buspirone Hydrochloride', 'Indonesia', 'ADVATE', '$3.13');
insert into product (id, brand, madein, name, price) values (37, 'Rimmel London', 'Honduras', 'Fenofibric Acid', '$1.38');
insert into product (id, brand, madein, name, price) values (38, 'Neutrogena Healthy Defense Daily Moisturizer', 'United States', 'Rizatriptan', '$1.94');
insert into product (id, brand, madein, name, price) values (39, 'IvyMed', 'Canada', 'ACNE SOLUTIONS CLEARING CONCEALER', '$1.40');
insert into product (id, brand, madein, name, price) values (40, 'Nystatin', 'Sri Lanka', 'Earwax Removal Aid', '$0.30');
insert into product (id, brand, madein, name, price) values (41, 'Hydralazine Hydrochloride', 'Russia', 'Ciclopirox Olamine', '$7.45');
insert into product (id, brand, madein, name, price) values (42, 'Aleve', 'Guatemala', 'dg health naproxen sodium', '$9.12');
insert into product (id, brand, madein, name, price) values (43, 'PROVIGIL', 'China', 'GEM BEAUTY AMETHYST REJUVENATION CREAM', '$6.04');
insert into product (id, brand, madein, name, price) values (44, 'Lidocaine', 'China', 'Welmedix HomeCare PRO Fragile Skin Protectant', '$2.30');
insert into product (id, brand, madein, name, price) values (45, 'AZACTAM', 'China', 'Balsam Poplar', '$9.41');
insert into product (id, brand, madein, name, price) values (46, 'Maximum Strength', 'Belize', 'mucus and chest congestion', '$9.39');
insert into product (id, brand, madein, name, price) values (47, 'RUMEX ACETOSELLA POLLEN', 'Malaysia', 'INSTANT HAND SANITIZER', '$2.20');
insert into product (id, brand, madein, name, price) values (48, 'napoleon PERDIS CHINA DOLL FOUNDATION BROAD SPECTRUM SPF 15 Look 2', 'China', 'Simvastatin', '$6.29');
insert into product (id, brand, madein, name, price) values (49, 'DOXEPIN HYDROCHLORIDE', 'Belarus', 'Etodolac', '$7.65');
insert into product (id, brand, madein, name, price) values (50, 'Auvi-Q', 'Indonesia', 'CD DiorSkin Forever Flawless Perfection Fusion Wear Makeup SPF 25 - 023', '$4.23');
